import * as vscode from "vscode";
import * as path from "path";
import * as os from "os";
import * as fs from "fs/promises";
import { djb2 } from "../infra/hash";

/** Kotlin channel for fwcd/kotlin-language-server (vscode-kotlin extension).
 *
 *  fwcd resolves its classpath as
 *      global script (~/.config/kotlin-language-server/classpath)
 *        .or(workspace scan: maven -> gradle -> in-tree kls-classpath)
 *        .or(backup)
 *  where `or` is first-non-empty: a global script that PRINTS anything
 *  short-circuits the workspace scan entirely, so the stray build.gradle
 *  files inside an AOSP tree are never touched — the "no gradle" guarantee
 *  comes for free, no importer switches needed. The script runs with the
 *  first workspace folder as CWD and dispatches on $PWD: known AOSP roots
 *  cat their jar list, anything else prints nothing and fwcd falls back
 *  to its normal gradle/maven resolution (zero pollution).
 *
 *  The shell resolver's currentBuildFileVersion is the default 1, so fwcd
 *  never caches script output — a rewritten script takes effect without
 *  restarting the language server. */

const SCRIPT_MARKER = "# aosp-nav managed";
const SCRIPT_NAME = "classpath"; // no extension: first candidate fwcd checks
const ROOT_MAP_KEY = "aosp-nav.kotlinRootMap"; // globalState: root -> {hash, matchPaths}
const OWN_DIR = "aosp-nav"; // subdir for per-root jar lists

interface RootEntry {
  hash: string;
  matchPaths: string[]; // root itself + workspace folders inside it (fwcd CWDs)
}

export interface KotlinApplyResult {
  changed: boolean; // the script or a jar list was rewritten this call
  blocked: boolean; // a user-managed script exists; channel not taken over
  jars: number;
}

export type ScriptState = "ours" | "user" | "none";

let warnedUserScript = false;

function configBase(): string {
  // mirrors ShellClassPathResolver: XDG_CONFIG_HOME ?? ~/.config
  return process.env.XDG_CONFIG_HOME || path.join(os.homedir(), ".config");
}

function klsConfigDir(): string {
  return path.join(configBase(), "kotlin-language-server");
}

function scriptPath(): string {
  return path.join(klsConfigDir(), SCRIPT_NAME);
}

/** Every global script candidate fwcd could pick up (config dir names x
 *  platform extensions). Our SCRIPT_PATH is the very first on linux. */
function allGlobalScriptCandidates(): string[] {
  const exts = process.platform === "win32"
    ? [".bat", ".cmd", ".ps1"]
    : ["", ".sh", ".bash"];
  const names = ["kotlin-language-server", "KotlinLanguageServer"];
  const out: string[] = [];
  for (const n of names) for (const e of exts) out.push(path.join(configBase(), n, `classpath${e}`));
  return out;
}

async function readIfExists(p: string): Promise<string | null> {
  try {
    return await fs.readFile(p, "utf8");
  } catch {
    return null;
  }
}

/** Paths that fwcd may use as CWD for this root: the AOSP root itself plus
 *  any file-scheme workspace folder located inside it (sub-checkouts like
 *  frameworks/base opened as the workspace folder). */
function matchPathsFor(root: string): string[] {
  const paths = new Set<string>([root]);
  for (const f of vscode.workspace.workspaceFolders ?? []) {
    if (f.uri.scheme !== "file") continue;
    const p = f.uri.fsPath;
    if (p === root || p.startsWith(root + path.sep)) paths.add(p);
  }
  return [...paths];
}

function jarListPath(hash: string): string {
  return path.join(klsConfigDir(), OWN_DIR, `${hash}.txt`);
}

function buildScript(map: Record<string, RootEntry>): string {
  const lines: string[] = [
    "#!/bin/sh",
    `${SCRIPT_MARKER} -- regenerated by aosp-nav-vscode; do not edit.`,
    "# Dispatches the fwcd kotlin-language-server classpath by workspace root.",
    "# Unmatched roots print nothing so fwcd falls back to gradle/maven.",
    'case "$PWD" in',
  ];
  for (const e of Object.values(map)) {
    const txt = jarListPath(e.hash);
    for (const mp of e.matchPaths) {
      lines.push(`  "${mp}") cat "${txt}" ;;`);
    }
  }
  lines.push("esac", "exit 0", "");
  return lines.join("\n");
}

/** Write the jar list + global dispatch script for one AOSP root. Never
 *  throws: a filesystem failure is logged and reported via changed=false so
 *  the Java channel is unaffected. Safe to run repeatedly; content is
 *  compared before writing. */
export async function applyKotlinClasspath(
  ctx: vscode.ExtensionContext,
  root: string,
  jars: string[],
  log: (msg: string) => void
): Promise<KotlinApplyResult> {
  try {
    const script = scriptPath();

    // guard: any user-managed global script means we must not take over
    // (writing ours would shadow theirs for every non-AOSP project)
    const current = await readIfExists(script);
    if (current !== null && !current.includes(SCRIPT_MARKER)) {
      log(`[aosp-nav] kotlin: user-managed ${script} present, not taking over`);
      if (!warnedUserScript) {
        warnedUserScript = true;
        void vscode.window.showWarningMessage(vscode.l10n.t(
          "[aosp-nav] A user-managed kotlin-language-server classpath script already exists; aosp-nav will not take over the Kotlin classpath channel."
        ));
      }
      return { changed: false, blocked: true, jars: 0 };
    }
    for (const cand of allGlobalScriptCandidates()) {
      if (cand === script) continue;
      if ((await readIfExists(cand)) !== null) {
        log(`[aosp-nav] kotlin: user-managed ${cand} present, not taking over`);
        if (!warnedUserScript) {
          warnedUserScript = true;
          void vscode.window.showWarningMessage(vscode.l10n.t(
            "[aosp-nav] A user-managed kotlin-language-server classpath script already exists; aosp-nav will not take over the Kotlin classpath channel."
          ));
        }
        return { changed: false, blocked: true, jars: 0 };
      }
    }

    const map = ctx.globalState.get<Record<string, RootEntry>>(ROOT_MAP_KEY) ?? {};
    const prev = map[root];
    const matchPaths = prev
      ? [...new Set([...prev.matchPaths, ...matchPathsFor(root)])]
      : matchPathsFor(root);
    const entry: RootEntry = { hash: djb2(root), matchPaths };
    map[root] = entry;

    // per-root jar list (tmp + rename: two windows may share one root)
    const txt = jarListPath(entry.hash);
    await fs.mkdir(path.dirname(txt), { recursive: true });
    const content = jars.join(path.delimiter) + "\n";
    let txtChanged = false;
    if ((await readIfExists(txt)) !== content) {
      const tmp = `${txt}.${process.pid}.tmp`;
      await fs.writeFile(tmp, content);
      await fs.rename(tmp, txt);
      txtChanged = true;
    }

    // global dispatch script
    const next = buildScript(map);
    let scriptChanged = false;
    if (current !== next) {
      const tmp = `${script}.${process.pid}.tmp`;
      await fs.writeFile(tmp, next);
      await fs.rename(tmp, script);
      scriptChanged = true;
    }
    await fs.chmod(script, 0o755).catch(() => { /* best effort */ });

    await ctx.globalState.update(ROOT_MAP_KEY, map);
    log(`[aosp-nav] kotlin: ${jars.length} jars${txtChanged ? ` written (${path.basename(txt)})` : ""}${scriptChanged ? ", script updated" : ""}`);
    return { changed: txtChanged || scriptChanged, blocked: false, jars: jars.length };
  } catch (e) {
    log(`[aosp-nav] kotlin: failed to write classpath channel: ${e}`);
    return { changed: false, blocked: false, jars: 0 };
  }
}

/** Diagnostics probe: state of the global script + injected jar count for
 *  a root (0 = never injected / script missing). */
export async function probeKotlinChannel(root: string): Promise<{ script: ScriptState; jars: number }> {
  const script = scriptPath();
  const current = await readIfExists(script);
  let state: ScriptState = "none";
  if (current !== null) {
    state = current.includes(SCRIPT_MARKER) ? "ours" : "user";
  } else {
    for (const cand of allGlobalScriptCandidates()) {
      if (cand !== script && (await readIfExists(cand)) !== null) { state = "user"; break; }
    }
  }
  const txt = await readIfExists(jarListPath(djb2(root)));
  const jars = txt ? txt.trim().split(path.delimiter).filter(Boolean).length : 0;
  return { script: state, jars };
}

/** Rollback (aosp-nav.resetSettings): remove our script + jar lists. Never
 *  touches a user-managed script. */
export async function clearKotlinChannel(ctx: vscode.ExtensionContext): Promise<void> {
  const script = scriptPath();
  const current = await readIfExists(script);
  if (current !== null && current.includes(SCRIPT_MARKER)) {
    await fs.rm(script, { force: true });
  }
  await fs.rm(path.join(klsConfigDir(), OWN_DIR), { recursive: true, force: true }).catch(() => { /* best effort */ });
  await ctx.globalState.update(ROOT_MAP_KEY, undefined);
}
